# Generated by Django 4.0.2 on 2023-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0002_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
