# Generated by Django 4.0.2 on 2023-11-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0003_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='banner_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='cat_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='item_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='offer_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='order_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_user',
            name='user_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
    ]
