# Generated by Django 4.0.2 on 2023-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0005_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_user',
            name='arrival_access',
            field=models.CharField(blank=True, default='false', max_length=255, null=True),
        ),
    ]
