# Generated by Django 4.0.2 on 2023-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0008_service_history_date_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_user',
            name='arrival_access',
        ),
        migrations.AddField(
            model_name='profile_user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
